### ISSUE TITLE
Glitch in the diff or in the formatter?

### ISSUE THREAD

**Issue by mholt** [klauspost/asmfmt#1]
Very cool tool - glad to see something for cleaner assembly :+1:

In [example 2](https://files.klauspost.com/diff2.html), on line 2007 of the right side, it says:

```
	        ADCQ &nbnbsp;  p256const1<>(SB), ac
```

I don't know if that `&nbnbsp;` is intentional or part of the diff, but I just thought I'd ask about it.

**Comment by klauspost** [comment]
It is just in the diff tool.

[Source of the diff](https://github.com/klauspost/asmfmt/blob/master/testdata/p256_asm_amd64.golden#L2007).
