### ISSUE TITLE
asmfmt breaks macros starting with multi-line comments

### ISSUE THREAD

**Issue by jacobsa** [klauspost/asmfmt#22]
I love asmfmt, thanks for the great tool. I've come across one bug.

Given this input:

    // +build amd64,!gccgo,!appengine
    
    #define FOOBAR(ptr) \
    /*
     * Here is a
     * multi-line commant.
     */ \
            LEAL 15(ptr), AX; \
            RET;

asmfmt produces this:

    // +build amd64,!gccgo,!appengine
    
    #define FOOBAR(ptr) \
    /*
     * Here is a
     * multi-line commant.
     */
                              \
            LEAL 15(ptr), AX; \
            RET

Note that it's dropped the trailing `\` after the multi-line comment, breaking
the macro.

**Comment by klauspost** [comment]
Thanks for the detailed report.

It should be fixed with #23, which I will merge when the tests have passed.
