### ISSUE TITLE
NASM support

### ISSUE THREAD

**Issue by lassik** [klauspost/asmfmt#32]
Is anyone motivated to add explicit support for the NASM assembler? I'm already using asmfmt for NASM files and it works passably even now. It has never broken my code but a few things are formatted in a quirky way because it doesn't know about NASM syntax.

P.S. Great project, I was happy to learn that someone finally made an auto-formatter for assembly :)

**Comment by klauspost** [comment]
You are welcome to submit a PR, but I don't have plans to support this myself.
