### ISSUE TITLE
no space in multiline macro after TEXT?

### ISSUE THREAD

**Issue by akavel** [klauspost/asmfmt#4]
Not sure if that's planned, but TEXT in multiline macros seems [not to get space before backslash](https://github.com/klauspost/asmfmt/blob/c2d71ca96f9ac7e21040899c9ef59845de4ca5b2/testdata/asm_amd64.golden#L385); is that intended?

Sorry if that's required by parser or something; I'm not very experienced in Go's assembly, just had a look on this tool out of pure curiosity. Just reporting FYI, you're welcome to do whatever you please with this report.

**Comment by klauspost** [comment]
Yes - you are right - that looks strange. I will give it a closer look.

**Comment by klauspost** [comment]
The parameter length calculation was wrong. [Fixed in latest version](https://github.com/klauspost/asmfmt/blob/master/testdata/asm_amd64.golden#L385).

Thanks for the report.
