### ISSUE TITLE
Weird indentation for nasm macros

### ISSUE THREAD

**Issue by RechieKho** [klauspost/asmfmt#49]
Here is what I got after asmfmt my nasm file :
```asm 
    %macro FINISH 0 
    pusha
    call something 
    jc %%success
    call error
%%success:
    popa
    %endmacro
```

It is enclosed in a header guard.

**Comment by klauspost** [comment]
This is for Go (plan 9) assembly. It may or may not work on other formats and may need some manual tweaks
